-- Create Schools table
CREATE TABLE IF NOT EXISTS "schools" (
    "id" INTEGER NOT NULL CONSTRAINT "PK_schools" PRIMARY KEY AUTOINCREMENT,
    "name" TEXT NOT NULL COLLATE NOCASE,
    "short_name" TEXT NULL COLLATE NOCASE,
    "school_description" TEXT NULL COLLATE NOCASE,
    "truck_id" INTEGER NULL,
    "price" REAL NULL,
    "fee_description" TEXT NULL COLLATE NOCASE,
    "formula" REAL NULL,
    "visit_day" TEXT NULL COLLATE NOCASE,
    "visit_sequence" TEXT NULL COLLATE NOCASE,
    "contact_person" TEXT NULL COLLATE NOCASE,
    "contact_cell" TEXT NULL COLLATE NOCASE,
    "phone" TEXT NULL COLLATE NOCASE,
    "telephone" TEXT NULL COLLATE NOCASE,
    "fax" TEXT NULL COLLATE NOCASE,
    "email" TEXT NULL COLLATE NOCASE,
    "circulars_email" TEXT NULL COLLATE NOCASE,
    "address" TEXT NULL COLLATE NOCASE,
    "address2" TEXT NULL COLLATE NOCASE,
    "headmaster" TEXT NULL COLLATE NOCASE,
    "headmaster_cell" TEXT NULL COLLATE NOCASE,
    "is_active" INTEGER NOT NULL DEFAULT 1,
    "language" TEXT NULL COLLATE NOCASE,
    "print_invoice" INTEGER NOT NULL DEFAULT 0,
    "import_flag" INTEGER NOT NULL DEFAULT 0,
    "afterschool1_name" TEXT NULL COLLATE NOCASE,
    "afterschool1_contact" TEXT NULL COLLATE NOCASE,
    "afterschool2_name" TEXT NULL COLLATE NOCASE,
    "afterschool2_contact" TEXT NULL COLLATE NOCASE,
    "scheduling_notes" TEXT NULL COLLATE NOCASE,
    "money_message" TEXT NULL COLLATE NOCASE,
    "safe_notes" TEXT NULL COLLATE NOCASE,
    "web_page" TEXT NULL COLLATE NOCASE,
    "omsendbriewe" TEXT NULL COLLATE NOCASE,
    "kcow_web_page_link" TEXT NULL COLLATE NOCASE,
    "created_at" TEXT NOT NULL DEFAULT (datetime('now')),
    "updated_at" TEXT NULL,
    CONSTRAINT "FK_schools_trucks_truck_id" FOREIGN KEY ("truck_id") REFERENCES "trucks" ("id") ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS "IX_schools_is_active_name" ON "schools" ("is_active", "name");
