-- Create Students table
CREATE TABLE IF NOT EXISTS "students" (
    "id" INTEGER NOT NULL CONSTRAINT "PK_students" PRIMARY KEY AUTOINCREMENT,
    "reference" TEXT NOT NULL COLLATE NOCASE,
    "first_name" TEXT NULL COLLATE NOCASE,
    "last_name" TEXT NULL COLLATE NOCASE,
    "date_of_birth" TEXT NULL,
    "gender" TEXT NULL COLLATE NOCASE,
    "language" TEXT NULL COLLATE NOCASE,
    "account_person_name" TEXT NULL COLLATE NOCASE,
    "account_person_surname" TEXT NULL COLLATE NOCASE,
    "account_person_id_number" TEXT NULL COLLATE NOCASE,
    "account_person_cellphone" TEXT NULL COLLATE NOCASE,
    "account_person_office" TEXT NULL COLLATE NOCASE,
    "account_person_home" TEXT NULL COLLATE NOCASE,
    "account_person_email" TEXT NULL COLLATE NOCASE,
    "relation" TEXT NULL COLLATE NOCASE,
    "mother_name" TEXT NULL COLLATE NOCASE,
    "mother_surname" TEXT NULL COLLATE NOCASE,
    "mother_office" TEXT NULL COLLATE NOCASE,
    "mother_cell" TEXT NULL COLLATE NOCASE,
    "mother_home" TEXT NULL COLLATE NOCASE,
    "mother_email" TEXT NULL COLLATE NOCASE,
    "father_name" TEXT NULL COLLATE NOCASE,
    "father_surname" TEXT NULL COLLATE NOCASE,
    "father_office" TEXT NULL COLLATE NOCASE,
    "father_cell" TEXT NULL COLLATE NOCASE,
    "father_home" TEXT NULL COLLATE NOCASE,
    "father_email" TEXT NULL COLLATE NOCASE,
    "address1" TEXT NULL COLLATE NOCASE,
    "address2" TEXT NULL COLLATE NOCASE,
    "postal_code" TEXT NULL COLLATE NOCASE,
    "school_name" TEXT NULL COLLATE NOCASE,
    "school_id" INTEGER NULL,
    "class_group_code" TEXT NULL COLLATE NOCASE,
    "class_group_id" INTEGER NULL,
    "grade" TEXT NULL COLLATE NOCASE,
    "teacher" TEXT NULL COLLATE NOCASE,
    "attending_kcow_at" TEXT NULL COLLATE NOCASE,
    "aftercare" TEXT NULL COLLATE NOCASE,
    "extra" TEXT NULL COLLATE NOCASE,
    "home_time" TEXT NULL,
    "start_classes" TEXT NULL,
    "terms" TEXT NULL COLLATE NOCASE,
    "seat" TEXT NULL COLLATE NOCASE,
    "truck" TEXT NULL COLLATE NOCASE,
    "family" TEXT NULL COLLATE NOCASE,
    "sequence" TEXT NULL COLLATE NOCASE,
    "financial_code" TEXT NULL COLLATE NOCASE,
    "charge" REAL NULL,
    "deposit" TEXT NULL COLLATE NOCASE,
    "pay_date" TEXT NULL COLLATE NOCASE,
    "tshirt_code" TEXT NULL COLLATE NOCASE,
    "tshirt_money_1" TEXT NULL COLLATE NOCASE,
    "tshirt_money_date_1" TEXT NULL,
    "tshirt_received_1" TEXT NULL COLLATE NOCASE,
    "tshirt_rec_date_1" TEXT NULL,
    "receive_note_1" TEXT NULL COLLATE NOCASE,
    "tshirt_size1" TEXT NULL COLLATE NOCASE,
    "tshirt_color1" TEXT NULL COLLATE NOCASE,
    "tshirt_design1" TEXT NULL COLLATE NOCASE,
    "tshirt_size2" TEXT NULL COLLATE NOCASE,
    "tshirt_money_2" TEXT NULL COLLATE NOCASE,
    "tshirt_money_date_2" TEXT NULL,
    "tshirt_received_2" TEXT NULL COLLATE NOCASE,
    "tshirt_rec_date_2" TEXT NULL,
    "receive_note_2" TEXT NULL COLLATE NOCASE,
    "tshirt_color2" TEXT NULL COLLATE NOCASE,
    "tshirt_design2" TEXT NULL COLLATE NOCASE,
    "indicator1" TEXT NULL COLLATE NOCASE,
    "indicator2" TEXT NULL COLLATE NOCASE,
    "general_note" TEXT NULL COLLATE NOCASE,
    "print_id_card" INTEGER NOT NULL DEFAULT 0,
    "accept_terms_cond" TEXT NULL COLLATE NOCASE,
    "status" TEXT NULL COLLATE NOCASE,
    "sms_or_email" TEXT NULL COLLATE NOCASE,
    "school_close" TEXT NULL,
    "cnt" REAL NULL,
    "online_entry" INTEGER NULL,
    "created" TEXT NULL,
    "submitted" TEXT NULL,
    "updated" TEXT NULL,
    "book_email" TEXT NULL COLLATE NOCASE,
    "report1_given_out" TEXT NULL COLLATE NOCASE,
    "account_given_out" TEXT NULL COLLATE NOCASE,
    "certificate_printed" TEXT NULL COLLATE NOCASE,
    "report2_given_out" TEXT NULL COLLATE NOCASE,
    "social" TEXT NULL COLLATE NOCASE,
    "activity_report_given_out" TEXT NULL COLLATE NOCASE,
    "photo_url" TEXT NULL COLLATE NOCASE,
    "photo_updated" TEXT NULL,
    "is_active" INTEGER NOT NULL DEFAULT 1,
    "created_at" TEXT NOT NULL DEFAULT (datetime('now')),
    "updated_at" TEXT NULL,
    CONSTRAINT "FK_students_schools_school_id" FOREIGN KEY ("school_id") REFERENCES "schools" ("id") ON DELETE SET NULL,
    CONSTRAINT "FK_students_class_groups_class_group_id" FOREIGN KEY ("class_group_id") REFERENCES "class_groups" ("id") ON DELETE SET NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS "ix_students_reference" ON "students" ("reference");
CREATE INDEX IF NOT EXISTS "ix_students_school_id" ON "students" ("school_id");
CREATE INDEX IF NOT EXISTS "ix_students_class_group_id" ON "students" ("class_group_id");
CREATE INDEX IF NOT EXISTS "ix_students_last_name" ON "students" ("last_name");
