CREATE TABLE IF NOT EXISTS "activities" (
    "id" INTEGER NOT NULL CONSTRAINT "PK_activities" PRIMARY KEY,
    "program" TEXT NULL COLLATE NOCASE,
    "program_name" TEXT NULL COLLATE NOCASE,
    "educational_focus" TEXT NULL COLLATE NOCASE,
    "folder" TEXT NULL COLLATE NOCASE,
    "grade" TEXT NULL COLLATE NOCASE,
    "icon" BLOB NULL
);

CREATE TABLE IF NOT EXISTS "Roles" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_Roles" PRIMARY KEY AUTOINCREMENT,
    "Name" TEXT NOT NULL COLLATE NOCASE,
    "CreatedAt" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "schools" (
    "id" INTEGER NOT NULL CONSTRAINT "PK_schools" PRIMARY KEY AUTOINCREMENT,
    "name" TEXT NOT NULL COLLATE NOCASE,
    "short_name" TEXT NULL COLLATE NOCASE,
    "school_description" TEXT NULL COLLATE NOCASE,
    "truck_id" INTEGER NULL,
    "price" decimal(18,2) NULL,
    "fee_description" TEXT NULL COLLATE NOCASE,
    "formula" decimal(18,2) NULL,
    "visit_day" TEXT NULL COLLATE NOCASE,
    "visit_sequence" TEXT NULL COLLATE NOCASE,
    "contact_person" TEXT NULL COLLATE NOCASE,
    "contact_cell" TEXT NULL COLLATE NOCASE,
    "phone" TEXT NULL COLLATE NOCASE,
    "telephone" TEXT NULL COLLATE NOCASE,
    "fax" TEXT NULL COLLATE NOCASE,
    "email" TEXT NULL COLLATE NOCASE,
    "circulars_email" TEXT NULL COLLATE NOCASE,
    "address" TEXT NULL COLLATE NOCASE,
    "address2" TEXT NULL COLLATE NOCASE,
    "headmaster" TEXT NULL COLLATE NOCASE,
    "headmaster_cell" TEXT NULL COLLATE NOCASE,
    "is_active" INTEGER NOT NULL,
    "language" TEXT NULL COLLATE NOCASE,
    "print_invoice" INTEGER NOT NULL,
    "import_flag" INTEGER NOT NULL,
    "afterschool1_name" TEXT NULL COLLATE NOCASE,
    "afterschool1_contact" TEXT NULL COLLATE NOCASE,
    "afterschool2_name" TEXT NULL COLLATE NOCASE,
    "afterschool2_contact" TEXT NULL COLLATE NOCASE,
    "scheduling_notes" TEXT NULL COLLATE NOCASE,
    "money_message" TEXT NULL COLLATE NOCASE,
    "safe_notes" TEXT NULL COLLATE NOCASE,
    "web_page" TEXT NULL COLLATE NOCASE,
    "omsendbriewe" TEXT NULL COLLATE NOCASE,
    "kcow_web_page_link" TEXT NULL COLLATE NOCASE,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NULL
);

CREATE TABLE IF NOT EXISTS "trucks" (
    "id" INTEGER NOT NULL CONSTRAINT "PK_trucks" PRIMARY KEY AUTOINCREMENT,
    "name" TEXT NOT NULL COLLATE NOCASE,
    "registration_number" TEXT NOT NULL COLLATE NOCASE,
    "status" TEXT NOT NULL COLLATE NOCASE,
    "notes" TEXT NULL COLLATE NOCASE,
    "is_active" INTEGER NOT NULL,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NULL
);

CREATE TABLE IF NOT EXISTS "Users" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_Users" PRIMARY KEY AUTOINCREMENT,
    "Email" TEXT NOT NULL COLLATE NOCASE,
    "PasswordHash" TEXT NOT NULL,
    "Name" TEXT NOT NULL COLLATE NOCASE,
    "RoleId" INTEGER NOT NULL,
    "CreatedAt" TEXT NOT NULL,
    "UpdatedAt" TEXT NOT NULL,
    CONSTRAINT "FK_Users_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS "class_groups" (
    "id" INTEGER NOT NULL CONSTRAINT "PK_class_groups" PRIMARY KEY AUTOINCREMENT,
    "name" TEXT NOT NULL COLLATE NOCASE,
    "day_truck" TEXT NULL COLLATE NOCASE,
    "description" TEXT NULL COLLATE NOCASE,
    "school_id" INTEGER NOT NULL,
    "truck_id" INTEGER NULL,
    "day_of_week" INTEGER NOT NULL,
    "start_time" TEXT NOT NULL,
    "end_time" TEXT NOT NULL,
    "sequence" INTEGER NOT NULL,
    "evaluate" INTEGER NOT NULL,
    "notes" TEXT NULL COLLATE NOCASE,
    "import_flag" INTEGER NOT NULL,
    "group_message" TEXT NULL COLLATE NOCASE,
    "send_certificates" TEXT NULL COLLATE NOCASE,
    "money_message" TEXT NULL COLLATE NOCASE,
    "ixl" TEXT NULL COLLATE NOCASE,
    "is_active" INTEGER NOT NULL,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NULL,
    CONSTRAINT "FK_class_groups_schools_school_id" FOREIGN KEY ("school_id") REFERENCES "schools" ("id") ON DELETE RESTRICT,
    CONSTRAINT "FK_class_groups_trucks_truck_id" FOREIGN KEY ("truck_id") REFERENCES "trucks" ("id") ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS "students" (
    "id" INTEGER NOT NULL CONSTRAINT "PK_students" PRIMARY KEY AUTOINCREMENT,
    "reference" TEXT NOT NULL COLLATE NOCASE,
    "first_name" TEXT NULL COLLATE NOCASE,
    "last_name" TEXT NULL COLLATE NOCASE,
    "date_of_birth" TEXT NULL,
    "gender" TEXT NULL COLLATE NOCASE,
    "language" TEXT NULL COLLATE NOCASE,
    "account_person_name" TEXT NULL COLLATE NOCASE,
    "account_person_surname" TEXT NULL COLLATE NOCASE,
    "account_person_id_number" TEXT NULL COLLATE NOCASE,
    "account_person_cellphone" TEXT NULL COLLATE NOCASE,
    "account_person_office" TEXT NULL COLLATE NOCASE,
    "account_person_home" TEXT NULL COLLATE NOCASE,
    "account_person_email" TEXT NULL COLLATE NOCASE,
    "relation" TEXT NULL COLLATE NOCASE,
    "mother_name" TEXT NULL COLLATE NOCASE,
    "mother_surname" TEXT NULL COLLATE NOCASE,
    "mother_office" TEXT NULL COLLATE NOCASE,
    "mother_cell" TEXT NULL COLLATE NOCASE,
    "mother_home" TEXT NULL COLLATE NOCASE,
    "mother_email" TEXT NULL COLLATE NOCASE,
    "father_name" TEXT NULL COLLATE NOCASE,
    "father_surname" TEXT NULL COLLATE NOCASE,
    "father_office" TEXT NULL COLLATE NOCASE,
    "father_cell" TEXT NULL COLLATE NOCASE,
    "father_home" TEXT NULL COLLATE NOCASE,
    "father_email" TEXT NULL COLLATE NOCASE,
    "address1" TEXT NULL COLLATE NOCASE,
    "address2" TEXT NULL COLLATE NOCASE,
    "postal_code" TEXT NULL COLLATE NOCASE,
    "school_name" TEXT NULL COLLATE NOCASE,
    "school_id" INTEGER NULL,
    "class_group_code" TEXT NULL COLLATE NOCASE,
    "class_group_id" INTEGER NULL,
    "grade" TEXT NULL COLLATE NOCASE,
    "teacher" TEXT NULL COLLATE NOCASE,
    "attending_kcow_at" TEXT NULL COLLATE NOCASE,
    "aftercare" TEXT NULL COLLATE NOCASE,
    "extra" TEXT NULL COLLATE NOCASE,
    "home_time" TEXT NULL,
    "start_classes" TEXT NULL,
    "terms" TEXT NULL COLLATE NOCASE,
    "seat" TEXT NULL COLLATE NOCASE,
    "truck" TEXT NULL COLLATE NOCASE,
    "family" TEXT NULL COLLATE NOCASE,
    "sequence" TEXT NULL COLLATE NOCASE,
    "financial_code" TEXT NULL COLLATE NOCASE,
    "charge" decimal(18,2) NULL,
    "deposit" TEXT NULL COLLATE NOCASE,
    "pay_date" TEXT NULL COLLATE NOCASE,
    "tshirt_code" TEXT NULL COLLATE NOCASE,
    "tshirt_money_1" TEXT NULL COLLATE NOCASE,
    "tshirt_money_date_1" TEXT NULL,
    "tshirt_received_1" TEXT NULL COLLATE NOCASE,
    "tshirt_rec_date_1" TEXT NULL,
    "receive_note_1" TEXT NULL COLLATE NOCASE,
    "tshirt_size1" TEXT NULL COLLATE NOCASE,
    "tshirt_color1" TEXT NULL COLLATE NOCASE,
    "tshirt_design1" TEXT NULL COLLATE NOCASE,
    "tshirt_size2" TEXT NULL COLLATE NOCASE,
    "tshirt_money_2" TEXT NULL COLLATE NOCASE,
    "tshirt_money_date_2" TEXT NULL,
    "tshirt_received_2" TEXT NULL COLLATE NOCASE,
    "tshirt_rec_date_2" TEXT NULL,
    "receive_note_2" TEXT NULL COLLATE NOCASE,
    "tshirt_color2" TEXT NULL COLLATE NOCASE,
    "tshirt_design2" TEXT NULL COLLATE NOCASE,
    "indicator1" TEXT NULL COLLATE NOCASE,
    "indicator2" TEXT NULL COLLATE NOCASE,
    "general_note" TEXT NULL COLLATE NOCASE,
    "print_id_card" INTEGER NOT NULL,
    "accept_terms_cond" TEXT NULL COLLATE NOCASE,
    "status" TEXT NULL COLLATE NOCASE,
    "sms_or_email" TEXT NULL COLLATE NOCASE,
    "school_close" TEXT NULL,
    "cnt" REAL NULL,
    "online_entry" INTEGER NULL,
    "created" TEXT NULL,
    "submitted" TEXT NULL,
    "updated" TEXT NULL,
    "book_email" TEXT NULL COLLATE NOCASE,
    "report1_given_out" TEXT NULL COLLATE NOCASE,
    "account_given_out" TEXT NULL COLLATE NOCASE,
    "certificate_printed" TEXT NULL COLLATE NOCASE,
    "report2_given_out" TEXT NULL COLLATE NOCASE,
    "social" TEXT NULL COLLATE NOCASE,
    "activity_report_given_out" TEXT NULL COLLATE NOCASE,
    "photo_url" TEXT NULL COLLATE NOCASE,
    "photo_updated" TEXT NULL,
    "is_active" INTEGER NOT NULL,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NULL,
    CONSTRAINT "FK_students_class_groups_class_group_id" FOREIGN KEY ("class_group_id") REFERENCES "class_groups" ("id") ON DELETE RESTRICT,
    CONSTRAINT "FK_students_schools_school_id" FOREIGN KEY ("school_id") REFERENCES "schools" ("id") ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS "ix_class_groups_school_day_time" ON "class_groups" ("school_id", "day_of_week", "start_time");
CREATE INDEX IF NOT EXISTS "IX_class_groups_truck_id" ON "class_groups" ("truck_id");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Roles_Name" ON "Roles" ("Name");
CREATE INDEX IF NOT EXISTS "IX_schools_is_active_name" ON "schools" ("is_active", "name");
CREATE INDEX IF NOT EXISTS "ix_students_class_group_id" ON "students" ("class_group_id");
CREATE INDEX IF NOT EXISTS "ix_students_last_name" ON "students" ("last_name");
CREATE UNIQUE INDEX IF NOT EXISTS "ix_students_reference" ON "students" ("reference");
CREATE INDEX IF NOT EXISTS "ix_students_school_id" ON "students" ("school_id");
CREATE INDEX IF NOT EXISTS "IX_trucks_is_active" ON "trucks" ("is_active");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_trucks_registration_number" ON "trucks" ("registration_number");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Users_Email" ON "Users" ("Email");
CREATE INDEX IF NOT EXISTS "IX_Users_RoleId" ON "Users" ("RoleId");
