// <auto-generated />
using System;
using Kcow.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kcow.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260107060026_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("Kcow.Domain.Entities.Activity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("EducationalFocus")
                        .HasColumnType("TEXT")
                        .HasColumnName("educational_focus");

                    b.Property<string>("Folder")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("folder");

                    b.Property<string>("Grade")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("grade");

                    b.Property<byte[]>("Icon")
                        .HasColumnType("BLOB")
                        .HasColumnName("icon");

                    b.Property<string>("Program")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("program");

                    b.Property<string>("ProgramName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("program_name");

                    b.HasKey("Id");

                    b.ToTable("activities", (string)null);
                });

            modelBuilder.Entity("Kcow.Domain.Entities.ClassGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("INTEGER")
                        .HasColumnName("day_of_week");

                    b.Property<string>("DayTruck")
                        .HasMaxLength(6)
                        .HasColumnType("TEXT")
                        .HasColumnName("day_truck");

                    b.Property<string>("Description")
                        .HasMaxLength(35)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("end_time");

                    b.Property<bool>("Evaluate")
                        .HasColumnType("INTEGER")
                        .HasColumnName("evaluate");

                    b.Property<string>("GroupMessage")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("group_message");

                    b.Property<bool>("ImportFlag")
                        .HasColumnType("INTEGER")
                        .HasColumnName("import_flag");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("Ixl")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("ixl");

                    b.Property<string>("MoneyMessage")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("money_message");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<int>("SchoolId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("school_id");

                    b.Property<string>("SendCertificates")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("send_certificates");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sequence");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("start_time");

                    b.Property<int?>("TruckId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("truck_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TruckId");

                    b.HasIndex("SchoolId", "DayOfWeek", "StartTime")
                        .HasDatabaseName("ix_class_groups_school_day_time");

                    b.ToTable("class_groups", (string)null);
                });

            modelBuilder.Entity("Kcow.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Kcow.Domain.Entities.School", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("address");

                    b.Property<string>("Address2")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("address2");

                    b.Property<string>("Afterschool1Contact")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("afterschool1_contact");

                    b.Property<string>("Afterschool1Name")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("afterschool1_name");

                    b.Property<string>("Afterschool2Contact")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("afterschool2_contact");

                    b.Property<string>("Afterschool2Name")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("afterschool2_name");

                    b.Property<string>("CircularsEmail")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("circulars_email");

                    b.Property<string>("ContactCell")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("contact_cell");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("contact_person");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("Fax")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("fax");

                    b.Property<string>("FeeDescription")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("fee_description");

                    b.Property<decimal?>("Formula")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("formula");

                    b.Property<string>("Headmaster")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("headmaster");

                    b.Property<string>("HeadmasterCell")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("headmaster_cell");

                    b.Property<bool>("ImportFlag")
                        .HasColumnType("INTEGER")
                        .HasColumnName("import_flag");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("KcowWebPageLink")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("kcow_web_page_link");

                    b.Property<string>("Language")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("language");

                    b.Property<string>("MoneyMessage")
                        .HasColumnType("TEXT")
                        .HasColumnName("money_message");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Omsendbriewe")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("omsendbriewe");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("phone");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<bool>("PrintInvoice")
                        .HasColumnType("INTEGER")
                        .HasColumnName("print_invoice");

                    b.Property<string>("SafeNotes")
                        .HasColumnType("TEXT")
                        .HasColumnName("safe_notes");

                    b.Property<string>("SchedulingNotes")
                        .HasColumnType("TEXT")
                        .HasColumnName("scheduling_notes");

                    b.Property<string>("SchoolDescription")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("school_description");

                    b.Property<string>("ShortName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("short_name");

                    b.Property<string>("Telephone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("telephone");

                    b.Property<int?>("TruckId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("truck_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("VisitDay")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("visit_day");

                    b.Property<string>("VisitSequence")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("visit_sequence");

                    b.Property<string>("WebPage")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("web_page");

                    b.HasKey("Id");

                    b.HasIndex("IsActive", "Name");

                    b.ToTable("schools", (string)null);
                });

            modelBuilder.Entity("Kcow.Domain.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AcceptTermsCond")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("accept_terms_cond");

                    b.Property<string>("AccountGivenOut")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("account_given_out");

                    b.Property<string>("AccountPersonCellphone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("account_person_cellphone");

                    b.Property<string>("AccountPersonEmail")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("account_person_email");

                    b.Property<string>("AccountPersonHome")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("account_person_home");

                    b.Property<string>("AccountPersonIdNumber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("account_person_id_number");

                    b.Property<string>("AccountPersonName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("account_person_name");

                    b.Property<string>("AccountPersonOffice")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("account_person_office");

                    b.Property<string>("AccountPersonSurname")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("account_person_surname");

                    b.Property<string>("ActivityReportGivenOut")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("activity_report_given_out");

                    b.Property<string>("Address1")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("address1");

                    b.Property<string>("Address2")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("address2");

                    b.Property<string>("Aftercare")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("aftercare");

                    b.Property<string>("AttendingKcowAt")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("attending_kcow_at");

                    b.Property<string>("BookEmail")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("book_email");

                    b.Property<string>("CertificatePrinted")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("certificate_printed");

                    b.Property<decimal?>("Charge")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("charge");

                    b.Property<string>("ClassGroupCode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("class_group_code");

                    b.Property<int?>("ClassGroupId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("class_group_id");

                    b.Property<float?>("Cnt")
                        .HasColumnType("REAL")
                        .HasColumnName("cnt");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Deposit")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("deposit");

                    b.Property<string>("Extra")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("extra");

                    b.Property<string>("Family")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("family");

                    b.Property<string>("FatherCell")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("father_cell");

                    b.Property<string>("FatherEmail")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("father_email");

                    b.Property<string>("FatherHome")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("father_home");

                    b.Property<string>("FatherName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("father_name");

                    b.Property<string>("FatherOffice")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("father_office");

                    b.Property<string>("FatherSurname")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("father_surname");

                    b.Property<string>("FinancialCode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("financial_code");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("gender");

                    b.Property<string>("GeneralNote")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("general_note");

                    b.Property<string>("Grade")
                        .HasMaxLength(5)
                        .HasColumnType("TEXT")
                        .HasColumnName("grade");

                    b.Property<DateTime?>("HomeTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("home_time");

                    b.Property<string>("Indicator1")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("indicator1");

                    b.Property<string>("Indicator2")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("indicator2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("Language")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("language");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("last_name");

                    b.Property<DateTime?>("LegacyCreated")
                        .HasColumnType("TEXT")
                        .HasColumnName("created");

                    b.Property<DateTime?>("LegacyUpdated")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated");

                    b.Property<string>("MotherCell")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("mother_cell");

                    b.Property<string>("MotherEmail")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("mother_email");

                    b.Property<string>("MotherHome")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("mother_home");

                    b.Property<string>("MotherName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("mother_name");

                    b.Property<string>("MotherOffice")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("mother_office");

                    b.Property<string>("MotherSurname")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("mother_surname");

                    b.Property<int?>("OnlineEntry")
                        .HasColumnType("INTEGER")
                        .HasColumnName("online_entry");

                    b.Property<string>("PayDate")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("pay_date");

                    b.Property<DateTime?>("PhotoUpdated")
                        .HasColumnType("TEXT")
                        .HasColumnName("photo_updated");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("photo_url");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("postal_code");

                    b.Property<bool>("PrintIdCard")
                        .HasColumnType("INTEGER")
                        .HasColumnName("print_id_card");

                    b.Property<string>("ReceiveNote1")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("receive_note_1");

                    b.Property<string>("ReceiveNote2")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("receive_note_2");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("reference");

                    b.Property<string>("Relation")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("relation");

                    b.Property<string>("Report1GivenOut")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("report1_given_out");

                    b.Property<string>("Report2GivenOut")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("report2_given_out");

                    b.Property<DateTime?>("SchoolClose")
                        .HasColumnType("TEXT")
                        .HasColumnName("school_close");

                    b.Property<int?>("SchoolId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("school_id");

                    b.Property<string>("SchoolName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("school_name");

                    b.Property<string>("Seat")
                        .HasMaxLength(5)
                        .HasColumnType("TEXT")
                        .HasColumnName("seat");

                    b.Property<string>("Sequence")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("sequence");

                    b.Property<string>("SmsOrEmail")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("sms_or_email");

                    b.Property<string>("Social")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("social");

                    b.Property<DateTime?>("StartClasses")
                        .HasColumnType("TEXT")
                        .HasColumnName("start_classes");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<DateTime?>("Submitted")
                        .HasColumnType("TEXT")
                        .HasColumnName("submitted");

                    b.Property<string>("Teacher")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("teacher");

                    b.Property<string>("Terms")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("terms");

                    b.Property<string>("Truck")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("truck");

                    b.Property<string>("TshirtCode")
                        .HasMaxLength(4)
                        .HasColumnType("TEXT")
                        .HasColumnName("tshirt_code");

                    b.Property<string>("TshirtColor1")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("tshirt_color1");

                    b.Property<string>("TshirtColor2")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("tshirt_color2");

                    b.Property<string>("TshirtDesign1")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("tshirt_design1");

                    b.Property<string>("TshirtDesign2")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("tshirt_design2");

                    b.Property<string>("TshirtMoney1")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("tshirt_money_1");

                    b.Property<string>("TshirtMoney2")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("tshirt_money_2");

                    b.Property<DateTime?>("TshirtMoneyDate1")
                        .HasColumnType("TEXT")
                        .HasColumnName("tshirt_money_date_1");

                    b.Property<DateTime?>("TshirtMoneyDate2")
                        .HasColumnType("TEXT")
                        .HasColumnName("tshirt_money_date_2");

                    b.Property<DateTime?>("TshirtRecDate1")
                        .HasColumnType("TEXT")
                        .HasColumnName("tshirt_rec_date_1");

                    b.Property<DateTime?>("TshirtRecDate2")
                        .HasColumnType("TEXT")
                        .HasColumnName("tshirt_rec_date_2");

                    b.Property<string>("TshirtReceived1")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("tshirt_received_1");

                    b.Property<string>("TshirtReceived2")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("tshirt_received_2");

                    b.Property<string>("TshirtSize1")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("tshirt_size1");

                    b.Property<string>("TshirtSize2")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("tshirt_size2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ClassGroupId")
                        .HasDatabaseName("ix_students_class_group_id");

                    b.HasIndex("LastName")
                        .HasDatabaseName("ix_students_last_name");

                    b.HasIndex("Reference")
                        .IsUnique()
                        .HasDatabaseName("ix_students_reference");

                    b.HasIndex("SchoolId")
                        .HasDatabaseName("ix_students_school_id");

                    b.ToTable("students", (string)null);
                });

            modelBuilder.Entity("Kcow.Domain.Entities.Truck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("registration_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("RegistrationNumber")
                        .IsUnique();

                    b.ToTable("trucks", (string)null);
                });

            modelBuilder.Entity("Kcow.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Kcow.Domain.Entities.ClassGroup", b =>
                {
                    b.HasOne("Kcow.Domain.Entities.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kcow.Domain.Entities.Truck", "Truck")
                        .WithMany()
                        .HasForeignKey("TruckId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("School");

                    b.Navigation("Truck");
                });

            modelBuilder.Entity("Kcow.Domain.Entities.Student", b =>
                {
                    b.HasOne("Kcow.Domain.Entities.ClassGroup", "ClassGroup")
                        .WithMany("Students")
                        .HasForeignKey("ClassGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Kcow.Domain.Entities.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ClassGroup");

                    b.Navigation("School");
                });

            modelBuilder.Entity("Kcow.Domain.Entities.User", b =>
                {
                    b.HasOne("Kcow.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Kcow.Domain.Entities.ClassGroup", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("Kcow.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
