// <auto-generated />
using System;
using Kcow.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kcow.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260105070442_UpdateSchoolFields")]
    partial class UpdateSchoolFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("Kcow.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Kcow.Domain.Entities.School", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("address");

                    b.Property<string>("Address2")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("address2");

                    b.Property<string>("Afterschool1Contact")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("afterschool1_contact");

                    b.Property<string>("Afterschool1Name")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("afterschool1_name");

                    b.Property<string>("Afterschool2Contact")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("afterschool2_contact");

                    b.Property<string>("Afterschool2Name")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("afterschool2_name");

                    b.Property<string>("BillingSettings")
                        .HasColumnType("TEXT")
                        .HasColumnName("billing_settings");

                    b.Property<string>("CircularsEmail")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("circulars_email");

                    b.Property<string>("ContactCell")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("contact_cell");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("contact_person");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("Fax")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("fax");

                    b.Property<string>("FeeDescription")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("fee_description");

                    b.Property<decimal?>("Formula")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("formula");

                    b.Property<string>("Headmaster")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("headmaster");

                    b.Property<string>("HeadmasterCell")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("headmaster_cell");

                    b.Property<bool>("ImportFlag")
                        .HasColumnType("INTEGER")
                        .HasColumnName("import_flag");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("KcowWebPageLink")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("kcow_web_page_link");

                    b.Property<string>("Language")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("language");

                    b.Property<string>("MoneyMessage")
                        .HasColumnType("TEXT")
                        .HasColumnName("money_message");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("phone");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<bool>("PrintInvoice")
                        .HasColumnType("INTEGER")
                        .HasColumnName("print_invoice");

                    b.Property<string>("SafeNotes")
                        .HasColumnType("TEXT")
                        .HasColumnName("safe_notes");

                    b.Property<string>("SchedulingNotes")
                        .HasColumnType("TEXT")
                        .HasColumnName("scheduling_notes");

                    b.Property<string>("ShortName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("short_name");

                    b.Property<string>("Telephone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("telephone");

                    b.Property<int?>("TruckId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("truck_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("VisitDay")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("visit_day");

                    b.Property<string>("VisitSequence")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("visit_sequence");

                    b.Property<string>("WebPage")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("web_page");

                    b.HasKey("Id");

                    b.HasIndex("IsActive", "Name");

                    b.ToTable("schools", (string)null);
                });

            modelBuilder.Entity("Kcow.Domain.Entities.Truck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("registration_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("RegistrationNumber")
                        .IsUnique();

                    b.ToTable("trucks", (string)null);
                });

            modelBuilder.Entity("Kcow.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Kcow.Domain.Entities.User", b =>
                {
                    b.HasOne("Kcow.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Kcow.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
