// <auto-generated />
using System;
using Kcow.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kcow.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("Kcow.Domain.Entities.ClassGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DayTruck")
                        .HasMaxLength(6)
                        .HasColumnType("TEXT")
                        .HasColumnName("day_truck");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("INTEGER")
                        .HasColumnName("day_of_week");

                    b.Property<string>("Description")
                        .HasMaxLength(35)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("end_time");

                    b.Property<bool>("Evaluate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("evaluate")
                        .HasDefaultValue(false);

                    b.Property<bool>("ImportFlag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("import_flag")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<string>("GroupMessage")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("group_message");

                    b.Property<string>("SendCertificates")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("send_certificates");

                    b.Property<string>("MoneyMessage")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("money_message");

                    b.Property<string>("Ixl")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("ixl");

                    b.Property<int>("SchoolId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("school_id");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sequence");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("start_time");

                    b.Property<int?>("TruckId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("truck_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TruckId");

                    b.HasIndex("SchoolId", "DayOfWeek", "StartTime")
                        .HasDatabaseName("ix_class_groups_school_day_time");

                    b.ToTable("class_groups", (string)null);
                });

            modelBuilder.Entity("Kcow.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Kcow.Domain.Entities.School", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("address");

                    b.Property<string>("Address2")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("address2");

                    b.Property<string>("Afterschool1Contact")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("afterschool1_contact");

                    b.Property<string>("Afterschool1Name")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("afterschool1_name");

                    b.Property<string>("Afterschool2Contact")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("afterschool2_contact");

                    b.Property<string>("Afterschool2Name")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("afterschool2_name");

                    b.Property<string>("CircularsEmail")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("circulars_email");

                    b.Property<string>("ContactCell")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("contact_cell");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("contact_person");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("Fax")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("fax");

                    b.Property<string>("FeeDescription")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("fee_description");

                    b.Property<decimal?>("Formula")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("formula");

                    b.Property<string>("Headmaster")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("headmaster");

                    b.Property<string>("HeadmasterCell")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("headmaster_cell");

                    b.Property<bool>("ImportFlag")
                        .HasColumnType("INTEGER")
                        .HasColumnName("import_flag");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("KcowWebPageLink")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("kcow_web_page_link");

                    b.Property<string>("Language")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("language");

                    b.Property<string>("MoneyMessage")
                        .HasColumnType("TEXT")
                        .HasColumnName("money_message");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("phone");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<bool>("PrintInvoice")
                        .HasColumnType("INTEGER")
                        .HasColumnName("print_invoice");

                    b.Property<string>("SafeNotes")
                        .HasColumnType("TEXT")
                        .HasColumnName("safe_notes");

                    b.Property<string>("SchedulingNotes")
                        .HasColumnType("TEXT")
                        .HasColumnName("scheduling_notes");

                    b.Property<string>("ShortName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("short_name");

                    b.Property<string>("Telephone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("telephone");

                    b.Property<int?>("TruckId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("truck_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("VisitDay")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("visit_day");

                    b.Property<string>("VisitSequence")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("visit_sequence");

                    b.Property<string>("WebPage")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("web_page");

                    b.HasKey("Id");

                    b.HasIndex("IsActive", "Name");

                    b.ToTable("schools", (string)null);
                });

            modelBuilder.Entity("Kcow.Domain.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClassGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClassGroupId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Kcow.Domain.Entities.Truck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("registration_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("RegistrationNumber")
                        .IsUnique();

                    b.ToTable("trucks", (string)null);
                });

            modelBuilder.Entity("Kcow.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Kcow.Domain.Entities.ClassGroup", b =>
                {
                    b.HasOne("Kcow.Domain.Entities.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kcow.Domain.Entities.Truck", "Truck")
                        .WithMany()
                        .HasForeignKey("TruckId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("School");

                    b.Navigation("Truck");
                });

            modelBuilder.Entity("Kcow.Domain.Entities.Student", b =>
                {
                    b.HasOne("Kcow.Domain.Entities.ClassGroup", null)
                        .WithMany("Students")
                        .HasForeignKey("ClassGroupId");
                });

            modelBuilder.Entity("Kcow.Domain.Entities.User", b =>
                {
                    b.HasOne("Kcow.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Kcow.Domain.Entities.ClassGroup", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("Kcow.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
